#!/bin/bash

export ROOT=`pwd`
export BUILD_DIR=/home/travis/build/pg
export SOURCE_DIR=$BUILD_DIR/src

export PGDATA=$BUILD_DIR/data
export PGPORT=5777
export PGHOST=localhost

export PG_BIN=$BUILD_DIR/bin
export PG_CONFIG=$BUILD_DIR

export PATH=$PATH:$PG_BIN

sudo apt-get -y -qq --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
sudo apt-get -qq update
sudo apt-get -qqy install \
  git \
  build-essential \
  gettext \
  libreadline6 \
  libreadline6-dev \
  zlib1g-dev \
  flex \
  bison \
  libxml2-dev \
  libxslt-dev

git clone -b REL9_4_STABLE --depth=1 git://git.postgresql.org/git/postgresql.git $SOURCE_DIR

# XML2_CONFIG=`which xml2-config` cd $SOURCE_DIR ./configure --prefix=$BUILD_DIR  --with-libxml &&\

cd $SOURCE_DIR && ./configure --prefix=$BUILD_DIR &&  make && make install


cd $ROOT && make USE_PGXS=1 && make install USE_PGXS=1

mkdir -p $PGDATA

$PG_BIN/initdb -D $PGDATA -E utf8

# echo "host all  all    0.0.0.0/0  md5" >> $PGDATA/pg_hba.conf
# echo "listen_addresses='*'" >> $PGDATA/postgresql.conf
# echo "port=$PGPORT" >> $PGDATA/postgresql.conf

$PG_BIN/pg_ctl -D $PGDATA start
