#!/bin/bash

export BUILD_DIR=/home/travis/build/pg
export SOURCE_DIR=$BUILD_DIR/src

export PGDATA=$BUILD_DIR/data
export PGPORT=5777
export PGHOST=localhost

export PG_BIN=$BUILD_DIR/bin
export PG_CONFIG=$BUILD_DIR

export PATH=$PATH:$PG_BIN

export ROOT=`pwd`

make installcheck USE_PGXS=1
